____
Amazon Simple Email Service (Amazon SES) is a cloud-based email sending service designed to help digital marketers and application developers send marketing, notification, and transactional emails. It is a reliable, cost-effective service for businesses of all sizes that use email to keep in contact with their customers.
____

Add a dependency to AWS SES SDK:

[source,groovy]
.build.gradle
----
include::{sourceDir}/build.gradle[tag=awsses]
----

Create a service which encapsulates AWS credentials provider. The bean will not be loaded if the
environment variables (`AWS_ACCESS_KEY_ID`, `AWS_SECRET_KEY`) or system properties ( `aws.accesskeyid`, `aws.secretkey`) are not present.

[source,kotlin]
.src/main/kotlin/example/micronaut/AwsCredentialsProviderCondition.kt
----
include::{sourceDir}/src/main/kotlin/example/micronaut/AwsCredentialsProviderCondition.kt[]
----

Add a test:

[source,kotlin]
.src/test/kotlin/example/micronaut/AwsCredentialsProviderConditionSpec.kt
----
include::{sourceDir}/src/test/kotlin/example/micronaut/AwsCredentialsProviderConditionSpec.kt[]
----

[source,kotlin]
.src/main/kotlin/example/micronaut/AwsCredentialsProviderService.kt
----
include::{sourceDir}/src/main/kotlin/example/micronaut/AwsCredentialsProviderService.kt[]
----

<1> Use `javax.inject.Singleton` to designate a class a a singleton
<2> Bean will not loaded unless condition is met.
<3> Values will be resolved from system properties.

Create a service which sends the email with AWS Simple Email Service. The bean will not be loaded if the
environment variables (`AWS_REGION`, `AWS_SOURCE_EMAIL`) or system properties (`aws.region`, `aws.sourceemail`) are not present.

[source,kotlin]
.src/main/kotlin/example/micronaut/AwsSesMailCondition.kt
----
include::{sourceDir}/src/main/kotlin/example/micronaut/AwsSesMailCondition.kt[]
----

Add a test:

[source,kotlin]
.src/test/kotlin/example/micronaut/AwsSesMailConditionSpec.kt
----
include::{sourceDir}/src/test/kotlin/example/micronaut/AwsSesMailConditionSpec.kt[]
----

[source,kotlin]
.src/main/kotlin/example/micronaut/AwsSesMailService.kt
----
include::{sourceDir}/src/main/kotlin/example/micronaut/AwsSesMailService.kt[]
----

<1> Use `javax.inject.Singleton` to designate a class a a singleton
<2> Bean will not loaded unless condition is met.
<3> `@Primary` is a qualifier that indicates that a bean is the primary bean that should be selected in the case of multiple possible interface implementations.
<4> Values will be resolved from system properties.


Add a test:

[source,kotlin]
.src/test/kotlin/example/micronaut/AwsSesMailServiceSpec.kt
----
include::{sourceDir}/src/test/kotlin/example/micronaut/AwsSesMailServiceSpec.kt[]
----
