We want to ensure any email request contains a subject, recipient and a text body or html body.

Micronaut's validation is built on with the standard framework – JSR 380, also known as Bean Validation 2.0.

Hibernate Validator is a reference implementation of the validation API.

Add a dependency to it:

[source,java]
.build.gradle
----
include::{sourceDir}/build.gradle[tag=hibernate-validator]
----

Create the next test:

[source,java]
.src/test/kotlin/example/micronaut/MailControllerValidationSpec.kt
----
include::{sourceDir}/src/test/kotlin/example/micronaut/MailControllerValidationSpec.kt[]
----

<1> To run the application from a unit test you can use the http://docs.micronaut.io/snapshot/api/io/micronaut/runtime/server/EmbeddedServer.html[EmbeddedServer] interface
<2> Register a `HttpClient` bean in the application context and point it to the embedded server URL. The `EmbeddedServer` interface provides the URL of the server under test which runs on a random port.
<3> Creating HTTP Requests is easy thanks to Micronaut's fluid API.

In order to satisfy the test, create an email constraints annotation

[source,java]
.src/main/java/example/micronaut/EmailConstraints.java
----
include::{sourceDir}/src/main/java/example/micronaut/EmailConstraints.java[]
----

and a validator:

[source,java]
.src/main/java/example/micronaut/EmailConstraintsValidator.java
----
include::{sourceDir}/src/main/java/example/micronaut/EmailConstraintsValidator.java[]
----

Annotate Email with `EmailConstraints`.

[source,java]
.src/main/kotlin/example/micronaut/EmailCmd.kt
----
include::{sourceDir}/src/main/kotlin/example/micronaut/EmailCmd.kt[tag=clazzwithannotations]

include::{sourceDir}/src/main/kotlin/example/micronaut/EmailCmd.kt[tag=properties]

include::{sourceDir}/src/main/kotlin/example/micronaut/EmailCmd.kt[tag=settersandgetters]

}
----