We want to ensure any email request contains a subject, recipient and a text body or html body.

include::{commondir}/common-validation.adoc[indent=0]

Create the next test:

[source,kotlin]
.src/test/kotlin/example/micronaut/MailControllerValidationSpec.kt
----
include::{sourceDir}/src/test/kotlin/example/micronaut/MailControllerValidationSpec.kt[]
----

<1> To run the application from a unit test you can use the http://docs.micronaut.io/snapshot/api/io/micronaut/runtime/server/EmbeddedServer.html[EmbeddedServer] interface
<2> Register a `HttpClient` bean in the application context and point it to the embedded server URL. The `EmbeddedServer` interface provides the URL of the server under test which runs on a random port.
<3> Creating HTTP Requests is easy thanks to Micronaut's fluid API.

In order to satisfy the test, create an email constraints annotation

[source,java]
.src/main/java/example/micronaut/EmailConstraints.java
----
include::{sourceDir}/src/main/java/example/micronaut/EmailConstraints.java[]
----

and a contraint validator in a `@Factory` class:

[source,java]
.src/main/java/example/micronaut/EmailConstraintsFactory.java
----
include::{sourceDir}/src/main/java/example/micronaut/EmailConstraintsFactory.java[]
----

Annotate `EmailCmd` with `EmailConstraints` and `@Introspected` (to generate the
https://docs.micronaut.io/latest/guide/index.html#introspection[Bean Introspection information]).

[source,kotlin]
.src/main/kotlin/example/micronaut/EmailCmd.kt
----
include::{sourceDir}/src/main/kotlin/example/micronaut/EmailCmd.kt[tag=clazzwithannotations]

include::{sourceDir}/src/main/kotlin/example/micronaut/EmailCmd.kt[tag=properties]

include::{sourceDir}/src/main/kotlin/example/micronaut/EmailCmd.kt[tag=settersandgetters]

}
----